# Generated by Django 5.0.2 on 2024-03-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
