# Generated by Django 5.0.2 on 2024-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_blog_post_publish_205817_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_size',
            field=models.ImageField(default='blog/next.jpg', upload_to='blog/'),
        ),
    ]
