# Generated by Django 5.0.2 on 2024-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Comment',
        ),
    ]
